SELECT i.BOOK_ID, b.TITLE, b.AUTHOR, (SUM(i.QUANTITY_SOLD) - SUM(NVL(r.QUANTITY_RETURNED, 0))) QUANTITY_SOLD
FROM ORDER_ITEMS i
JOIN BOOKS b
ON i.BOOK_ID = b.BOOK_ID
LEFT OUTER JOIN ORDER_RETURN r
ON i.ORDER_ID = r.ORDER_ID
AND i.BOOK_ID = r.BOOK_ID
GROUP BY i.BOOK_ID, b.TITLE, b.AUTHOR
ORDER BY QUANTITY_SOLD DESC
FETCH FIRST 3 ROWS ONLY;

SELECT c.CATEGORY_ID, c.CATEGORY_NAME, (SUM(i.QUANTITY_SOLD) - SUM(NVL(r.QUANTITY_RETURNED, 0))) QUANTITY_SOLD
FROM CATEGORIES c
JOIN BOOKS b
ON c.CATEGORY_ID = b.CATEGORY_ID
JOIN ORDER_ITEMS i
ON b.BOOK_ID = i.BOOK_ID
LEFT OUTER JOIN ORDER_RETURN r
ON i.ORDER_ID = r.ORDER_ID
AND i.BOOK_ID = r.BOOK_ID
GROUP BY c.CATEGORY_ID, c.CATEGORY_NAME
ORDER BY QUANTITY_SOLD DESC
FETCH FIRST 3 ROWS ONLY;